# Generated by Django 5.0.1 on 2024-04-19 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_flowersoption_select_flowers_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='select_flowers',
            new_name='selected_flowers',
        ),
    ]
