# Generated by Django 5.0.1 on 2024-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_flowersoption_season_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='next_payment_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paymeent_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='vendor',
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_type',
            field=models.IntegerField(choices=[(0, 'monthly'), (1, 'yearly')], default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
