# Generated by Django 5.0.1 on 2024-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_created_at_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
