# Generated by Django 5.0.4 on 2024-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_about_me_profile_about_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='xyz', max_length=150),
        ),
    ]
