# Generated by Django 5.0.1 on 2024-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_vendorprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media\\profile_image\\default.png', null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
